### ISSUE TITLE
Reformatting and Reworking Accounting Sheets and scripts

### ISSUE THREAD

**Issue by JaMaSiL** [hoprnet/hopr-devrel#132] opened 2021-12-13 08:51 UTC
Update Accounting workflow

----

For the annual financial statement for the HOPR Association, Q has created Dune scripts to track all wallets of HOPR Association. They must be redefined to [fit this format](https://docs.google.com/spreadsheets/d/1E6T8pnZQfiVL4e_RZA6-OKv8h32rOY2o)
----------

They include all needed information, but (a) do not have the correct format and (b) ALL transactions need to be associated with accountancy accounts. Therefore, for each transaction, an expense account and a revenue account must be defined. 
(Edit: see clarifications in comment)
A full list of all accounts exists already, as well as all transactions. It is unclear whether ALL wallets are accounted for (Dev wallets especially). 95% of the workload could be done with a simple macro and/or some queries. The rest will have to be manual labour that I can do by myself. 

 -----------
I would need to sit together with @QYuQianchen and @SCBuergel to discuss workflow, timeline and desired outcome.

**Comment by JaMaSiL** [comment] 2022-02-03 13:11
Clarifications:
- All wallets/currencies need their own account, meaning if the Multisig has five different coins, it needs five accounts
- The accounts for wallets/tokens should be in the 1000s range
- Only tokens for external use should be accounted for (if used for internal token only, no need)
- All marketing payments should be booked 6600 - HOPR Wallet Account
- If possible, differentiate between the different marketing efforts (use 6600 for bounties, 6601 for Hunt, 6602 for ambassadors etc.)
- All Grants are to be booked 4100- Hopr wallet account
- All salary payments for people employed by the Services AG should be booked 4100 - 2210
- The HOPR Boost should be Account 1200 (if used for marketing, this means 6600-1200)
- Ignore the "KST" fields
- Find all known [addresses here](https://docs.google.com/spreadsheets/d/1c2WjPGp8_3oXFVBUlmPeqWfFpjfjn7-l_lVKnFT5H2k/edit#gid=2039680702)

**Comment by QYuQianchen** [comment] 2022-02-11 08:55
Will work on this on the plane

**Comment by QYuQianchen** [comment] 2022-03-07 06:54
New [scripts is completed](https://script.google.com/home/projects/1Jbk0H9AzAV0N8clqWSUx426hlH_dnOFjaS8DC6_yA6mU4NnteTcQxYhU/edit). A new template: [0D - BDO TEMPLATE: Please fork me!](https://docs.google.com/spreadsheets/d/1ETCRKSnhyt6luzkEEH3BikAleMdW8kHlLlFZEpxVLrE/edit#gid=1948287466) is also introduced and [the README file](https://docs.google.com/document/d/1VOHYNmNxdf0qkYFwEVS_x3LRD2K9q1xSDPxq06Y83SI/edit#heading=h.ik0aqxqxcj7l) is updated to reflect the new creation process. Please only use the new template for new accounts from now on!

However, not all the old spreadsheets are updated. You can choose between:
1. Trash the old ones and create new ones. This is a preferred option when there are little to none manual entries in the old sheets. I saw half of the sheets haven't been synced since a few months. So this option could be the option to go for. 
2. Adapt the old ones: 
- overwrite script ("Extensions" -> "App scripts") with the [new one](https://script.google.com/home/projects/1Jbk0H9AzAV0N8clqWSUx426hlH_dnOFjaS8DC6_yA6mU4NnteTcQxYhU/edit) 
- open the template "0D - BDO TEMPLATE: Please fork me!" and navigate to the hidden "BDO template". Then "copy to" -> "existing spreadsheet" to the old accounting sheet of an account.

**Comment by QYuQianchen** [comment] 2022-03-08 15:10
After the sync call, updated the following in the script:

1. Add a token unit price summary page in "0E - account nr" sheet, where a flat unit price can be manually inserted.
2. Add transaction hash in column E
3. Auto-compute the "Betrag BasisWhg" (for fungible tokens: `amount * flat unit price`; for non-fungible tokens, `<token name> - <token id>`). Note that if you see `#REF` error, it means that an authorisation of linking another sheet needs to be confirmed; if you see `#N/A` error, means that this asset is not recognized properly, more debugging is needed; if the token unit price is not available, just update the corresponding value in "Token Price" of "0E - account nr" spreadsheet
4. Translate addresses in "Konto Soll" and "Konto Haben" into "Account nr".

**Comment by nionis** [comment] 2022-03-23 11:18
hey https://github.com/JaMaSiL, can you check the progress on this and let us know if there any changes that need to be done?

**Comment by QYuQianchen** [comment] 2022-03-24 14:31
As @JaMaSiL is off for approx. 2 weeks, we can close this for the moment and open a new issue on specific changes.

**Comment by nionis** [comment] 2022-03-25 14:26
Will wait for @JaMaSiL to give thumbs up on this and then close it.

**Comment by tolbrino** [comment] 2022-10-10 19:11
Closing since this is handled now separately

**Closed by tolbrino** 2022-10-10 19:11 UTC
Labels: enhancement, epic
